[package]
name = "rget"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
console = "0.15.8"
indicatif = "0.17.9"
reqwest = {version = "0.12.9", features = ["blocking"]}
url = "2.5.3"
futures-util = "0.3.31"
tokio = { version = "1", features = ["full"] }
